Corrected URI

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -113,16 +113,18 @@ jobs:
         run: |
           docker run --name solar-system-app -d \
             -p 3000:3000 \
-            -e MONGO_URI=$MONGO_URI \ 
-            -e MONGO_USERNAME=MONGO_USERNAME \
-            -e MONGO_PASSWORD=$MONGO_PASSWORD \
+            -e MONGO_URI="$MONGO_URI" \
+            -e MONGO_USERNAME="$MONGO_USERNAME" \
+            -e MONGO_PASSWORD="$MONGO_PASSWORD" \
             ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
 
           export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
           echo "Container IP: $IP"
 
           echo "Testing image url using wget"
-          wget -q -O - 127.0.0.1:3000/live || grep live
+          sleep 5
+          wget -q -O - http://127.0.0.1:3000/live || echo "Health check failed"
+
 
 
       - name: Docker push for testing
